-- D.I.S.C.O Preliminary Program V7.14 INTEGRATED STABILITY
-- Supabase SQL Editor에서 이 파일 전체를 1회 실행하세요.

alter table public.dpp_settings
  add column if not exists transition_locked boolean not null default false,
  add column if not exists transition_device_id text,
  add column if not exists transition_started_at timestamptz;

create table if not exists public.dpp_action_logs (
  id bigint generated by default as identity primary key,
  event_id text not null,
  action text not null,
  device_id text,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists dpp_action_logs_event_created_idx on public.dpp_action_logs(event_id,created_at desc);
alter table public.dpp_action_logs enable row level security;
drop policy if exists "dpp_action_logs_all" on public.dpp_action_logs;
create policy "dpp_action_logs_all" on public.dpp_action_logs for all using(true) with check(true);

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='dpp_action_logs') then
    alter publication supabase_realtime add table public.dpp_action_logs;
  end if;
end $$;

create or replace function public.dpp_activate_round2_v714(p_event_id text,p_device_id text default null)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_settings public.dpp_settings%rowtype;
  v_expected integer:=0;
  v_done integer:=0;
  v_count integer:=0;
  v_payload jsonb;
begin
  perform pg_advisory_xact_lock(hashtext(p_event_id));
  select * into v_settings from public.dpp_settings where event_id=p_event_id for update;
  if not found then raise exception '행사 설정을 찾지 못했습니다.'; end if;
  if coalesce(v_settings.round_phase,'round1_scoring')='round2_active' then
    return jsonb_build_object('ok',true,'already_active',true,'participant_count',(select count(*) from public.dpp_participants where event_id=p_event_id));
  end if;

  update public.dpp_settings set transition_locked=true,transition_device_id=p_device_id,transition_started_at=now(),is_ready=false,round_phase='round2_editing',updated_at=now() where event_id=p_event_id;

  if v_settings.scoring_mode='all' then
    select count(*)*3 into v_expected from public.dpp_participants where event_id=p_event_id;
  else
    select count(*) into v_expected from public.dpp_participants where event_id=p_event_id and participant_circle in ('A','B','C');
  end if;
  select count(*) into v_done from public.dpp_scores where event_id=p_event_id and score_mode=v_settings.scoring_mode and score is not null;
  if v_done<>v_expected then raise exception '점수 저장 미완료: %/%',v_done,v_expected; end if;

  select count(*) into v_count from public.dpp_round2_selection where event_id=p_event_id and selection_status='confirmed';
  if v_count=0 then raise exception '확정된 2차 명단이 없습니다.'; end if;
  if exists(select 1 from public.dpp_round2_selection where event_id=p_event_id and selection_status='confirmed' group by round2_order having count(*)>1) then raise exception '2차 ORDER가 중복되었습니다.'; end if;

  v_payload=jsonb_build_object('round',1,'scoring_mode',v_settings.scoring_mode,'top_count',v_settings.top_count,
    'participants',(select coalesce(jsonb_agg(to_jsonb(p) order by p.participant_order),'[]'::jsonb) from public.dpp_participants p where p.event_id=p_event_id),
    'scores',(select coalesce(jsonb_agg(to_jsonb(s) order by s.judge_circle,s.participant_order),'[]'::jsonb) from public.dpp_scores s where s.event_id=p_event_id and s.score_mode=v_settings.scoring_mode),
    'selected_round2',(select coalesce(jsonb_agg(to_jsonb(r) order by r.position),'[]'::jsonb) from public.dpp_round2_selection r where r.event_id=p_event_id and r.selection_status='confirmed'),
    'created_at',now());
  insert into public.dpp_round_archives(event_id,round_no,payload) values(p_event_id,1,v_payload);

  delete from public.dpp_logs where event_id=p_event_id;
  delete from public.dpp_scores where event_id=p_event_id;
  delete from public.dpp_participants where event_id=p_event_id;

  insert into public.dpp_participants(event_id,participant_order,participant_circle,participant_name,battle_name,updated_at)
    select event_id,round2_order,round2_circle,participant_name,battle_name,now()
    from public.dpp_round2_selection where event_id=p_event_id and selection_status='confirmed' order by position;

  if v_settings.scoring_mode='all' then
    insert into public.dpp_scores(event_id,score_mode,judge_circle,judge_name,participant_order,participant_circle,participant_name,battle_name,score,updated_at)
      select p.event_id,v_settings.scoring_mode,j.c,coalesce(v_settings.judges->j.c->>'name',j.c||' JUDGE'),p.participant_order,p.participant_circle,p.participant_name,p.battle_name,null,now()
      from public.dpp_participants p cross join (values('A'),('B'),('C')) j(c) where p.event_id=p_event_id;
  else
    insert into public.dpp_scores(event_id,score_mode,judge_circle,judge_name,participant_order,participant_circle,participant_name,battle_name,score,updated_at)
      select p.event_id,v_settings.scoring_mode,p.participant_circle,coalesce(v_settings.judges->p.participant_circle->>'name',p.participant_circle||' JUDGE'),p.participant_order,p.participant_circle,p.participant_name,p.battle_name,null,now()
      from public.dpp_participants p where p.event_id=p_event_id;
  end if;

  update public.dpp_settings set prelim_round=2,round_phase='round2_active',is_ready=true,transition_locked=false,transition_device_id=null,transition_started_at=null,updated_at=now() where event_id=p_event_id;
  insert into public.dpp_action_logs(event_id,action,device_id,detail) values(p_event_id,'round2_activated',p_device_id,jsonb_build_object('participants',v_count,'scores_verified',v_done));
  return jsonb_build_object('ok',true,'participant_count',v_count,'scores_verified',v_done);
exception when others then
  -- 함수 전체가 하나의 트랜잭션이므로 예외 발생 시 삭제/변경도 전부 롤백됩니다.
  raise;
end $$;

grant execute on function public.dpp_activate_round2_v714(text,text) to anon,authenticated;
