-- D.I.S.C.O Preliminary Program V7.12
-- Supabase SQL Editor에서 전체를 1회 실행

alter table public.dpp_settings
add column if not exists round_phase text not null default 'round1_scoring';

update public.dpp_settings
set round_phase =
  case
    when coalesce(prelim_round,1)=2 then 'round2_active'
    else 'round1_scoring'
  end
where round_phase is null
   or round_phase not in ('round1_scoring','round2_editing','round2_active');

create table if not exists public.dpp_round2_selection (
  id bigint generated by default as identity primary key,
  event_id text not null,
  source_order text not null,
  source_circle text,
  source_rank integer,
  participant_name text,
  battle_name text,
  position integer not null,
  round2_order text not null,
  round2_circle text not null,
  selection_status text not null default 'editing',
  updated_at timestamptz not null default now()
);

create unique index if not exists dpp_round2_selection_event_source_uidx
on public.dpp_round2_selection(event_id, source_order);

create index if not exists dpp_round2_selection_event_position_idx
on public.dpp_round2_selection(event_id, position);

alter table public.dpp_round2_selection enable row level security;

drop policy if exists "dpp_round2_selection_all" on public.dpp_round2_selection;
create policy "dpp_round2_selection_all"
on public.dpp_round2_selection
for all
using (true)
with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='dpp_round2_selection'
  ) then
    alter publication supabase_realtime
    add table public.dpp_round2_selection;
  end if;
end $$;
