-- D.I.S.C.O Preliminary Program V7.5 ROUND 2
-- Supabase SQL Editor에서 1회 실행

alter table public.dpp_settings
add column if not exists prelim_round integer not null default 1;

create table if not exists public.dpp_round_archives (
  id bigint generated by default as identity primary key,
  event_id text not null,
  round_no integer not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists dpp_round_archives_event_round_idx
on public.dpp_round_archives(event_id, round_no, created_at desc);

alter table public.dpp_round_archives enable row level security;

drop policy if exists "dpp_round_archives_all" on public.dpp_round_archives;
create policy "dpp_round_archives_all"
on public.dpp_round_archives
for all
using (true)
with check (true);

alter publication supabase_realtime add table public.dpp_round_archives;
